services:
  postgres:
    image: postgres:16-alpine
    container_name: devroast_db
    environment:
      POSTGRES_USER: devroast
      POSTGRES_PASSWORD: devroast_pass
      POSTGRES_DB: devroast
    ports:
      - "5433:5432"
    volumes:
      - devroast_pg_data:/var/lib/postgresql/data

volumes:
  devroast_pg_data:
